name = "persistence-website"

zone_id = '000fde296cba847a78e918414382ba7a'
account_id = '1b234fd75823c727716b84645046a3ff'
compatibility_flags = []
site = {bucket = "./build"}
main = "workers-site/index.js"
compatibility_date = "2022-06-06"

[env.staging]
route = 'https://staging.persistence.one/*'

[env.release]
route = 'https://persistence.one/*'
