name = "persistence-website"
type = "webpack"
compatibility_date = "2022-08-01"
account_id = "1b234fd75823c727716b84645046a3ff"
zone_id = '000fde296cba847a78e918414382ba7a'
usage_model = 'bundled'
compatibility_flags = []
site = {bucket = "./build"}
main = "workers-site/index.js"

[env.staging]
route = 'https://staging.persistence.one/*'

[env.release]
route = 'https://persistence.one/*'